<div class="jumbotron">
    <h1><?php echo $this->translate('Sell ticket') ?></h1>

    <form role="form">
        <div class="form-group">
            <label for="eventName"><?php echo $this->translate('Event name') ?></label>
            <input type="text" class="form-control" id="eventName" placeholder="<?php echo $this->translate('Enter event name') ?>">
        </div>
        <div class="form-group">
            <label for="eventName"><?php echo $this->translate('Event date') ?></label>
            <input type="text" class="form-control" id="eventName" placeholder="<?php echo $this->translate('Enter event date') ?>">
        </div>
        <div class="checkbox">
            <label>
                <input type="checkbox"> <?php echo $this->translate('I agree with terms and conditions') ?>
            </label>
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
    </form>
</div>